cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove',),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,  include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('shop.urls', namespace='shop')),
]


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

payment/urls.py
from django.urls import path
from . import views

app_name = 'payment'

urlpatterns = [
    path('process/', views.payment_process, name='process'),
    path('vaildataion/', views.payment_validation, name='validation'),

    path('completed/', views.payment_completed, name='completed'),
    path('failded/', views.payment_failed, name='failed'),

    path('canceled/', views.payment_canceled, name='canceled'),
]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path(
        '<slug:category_slug>/',
        views.product_list,
        name='product_list_by_category',
    ),
    path(
        '<int:id>/<slug:slug>/',
        views.product_detail,
        name='product_detail',
    ),
]

payment/models.py
from django.db import models
from orders.models import Order
from .payment_process import payment_prepare

import hashlib
# Create your models here.

class PaymentTransactionManager(models.Manager):
    def create_new(self,order,amount, success=None, transaction_status=None):
        if not order:
            raise ValueError("주문오류")
        
        order_hash = hashlib.sha1(str(order.id).encode('utf-8')).hexdigest()
        email_hash = "upgradeafterloginmodules"
        final_hash = hashlib.sha1((order_hash  + email_hash).encode('utf-8')).hexdigest()[:10]        
        merchant_order_id = "%s"%(final_hash)

        payment_prepare(merchant_uid= merchant_order_id, amount=amount)

        transaction = self.model(
            order = order,
            merchant_order_id=merchant_order_id,
            amount = amount
        )

        if success != None:
            transaction.success = success
            transaction.transaction_status = transaction_status
        
        try:
            transaction.save()
        except Exception as e:
            print("save error", e)
            raise e

        return transaction.merchant_order_id

class PaymentTransaction(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    merchant_order_id = models.CharField(max_length=120, null=True, blank=True)
    transaction_id = models.CharField(max_length=120, null=True, blank=True)
    amount = models.PositiveIntegerField(default=0)
    success = models.BooleanField(default=False)
    transaction_status = models.CharField(max_length=220, null=True, blank=True)
    type = models.DateTimeField(auto_now_add=True, auto_now=False)
    created = models.DateTimeField(auto_now_add=True,auto_now=False)

    objects = PaymentTransactionManager()

    def __str__(self):
        return str(self.order.id)
    
    class Meta:
        ordering = ['-created']

payment/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.conf import settings
from django.urls import reverse
from orders.models import Order
from .models import *

from decouple import config
from iamport import Iamport
from django.http import JsonResponse

from .payment_process import get_token

def payment_process(request):
    order_id = request.session.get('order_id')
    order = get_object_or_404(Order, id=order_id)
    shop_id = config('IAMPORT_SHOP_KEY')
    price = 0

    item_name = ""
    for item in order.items.all():
        item_name = item.product.name
        price = int(item.price)
   
    merchant_id = PaymentTransaction.objects.create_new(
        order=order,
        amount =price
    )

    context = {
        "order_id" : order_id,
        "shop_id" : shop_id,
        "merchant_id":merchant_id,
        "item_name":item_name,
        "amount":price
    }
    return render(request, 'payment/process.html', context)


def payment_validation(request):
    print('검증 함수 실행')
    if request.method == "POST":
        order_id = request.POST.get('order_id')
        order = Order.objects.get(id=order_id)
        merchant_id = request.POST.get('merchant_id')
        # merchant_id = PaymentTransaction.objects.get(order=order)
        imp_id = request.POST.get('imp_id')
        amount = request.POST.get('amount')
        print(f'port 안 데이터 {order_id}\n,{merchant_id}\n,{amount}\n,{order}\n')
        try:
            trans = PaymentTransaction.objects.get(
                order = order,
                merchant_order_id = merchant_id,
                amount = amount
            )
        except Exception as e:
            trans = None
        print(f'만들어진 주문데이터{trans}')
        if trans != None:
            trans.transaction_id = imp_id
            trans.success=True
            trans.save()
            order.paid =True
            order.save()

            data = {
                "works":True
            }
            print(f'처리후 데이터 {data}')
            return JsonResponse(data)
        else:
            return JsonResponse({}, status = 401)


def payment_completed(request):
    order_id = request.GET.get('order_id')
    order = Order.objects.get(id=order_id)
    return render(request, 'payment/complete.html', {'order':order})


def payment_failed(request):
    return render(request, 'payment/failed.html')

def payment_request(request):
    iamport = Iamport(
        imp_key = config('IAMPORT_API_KEY'),
        imp_secret = config('IAMPORT_REST_SECRET_KEY')
    )

    order_id = request.session.get('order_id')
    order = get_object_or_404(Order, id=order_id)
     
    merchant_uid = 'order_id_12345'
    amount = 100 

    try: 
        response = iamport.prepare(
            merchant_uid=merchant_uid,
            amount=amount
        )
    except Iamport.ResponseError as e:
        return JsonResponse({'error':e.message})
    

def check_payment(request, merchant_uid):
    iamport = Iamport(
        imp_key = config('IAMPORT_API_KEY'),
        imp_secret = config('IAMPORT_REST_SECRET_KEY')
    )

    #상품 아이디로 결재 정보 확인
    try:
        response =iamport.find(merchant_uid=merchant_uid)
        return JsonResponse(response)
    except Iamport.ResponseError as e:
        return JsonResponse({'error':e.error})
    

def verify_payment(request, product_price, merchant_uid):
    iamport = Iamport(
        imp_key = config('IAMPORT_API_KEY'),
        imp_secret = config('IAMPORT_REST_SECRET_KEY')
    )

    try:
        is_paid=iamport.is_paid(product_price, merchant_uid=merchant_uid)
        if is_paid:
            return JsonResponse({'message': 'Payment verified successfully'})
        else:
            return JsonResponse({'message':'payment verification failed'})
    except Iamport.ResponseError as e:
        return JsonResponse({'error':e.message})
    

def payment_canceled(request, merchant_uid):
    iamport = Iamport(
        imp_key = config('IAMPORT_API_KEY'),
        imp_secret = config('IAMPORT_REST_SECRET_KEY'))

    try:
       response = iamport.cancel('취소사유', merchant_uid=merchant_uid)
       return JsonResponse(response)
    except Iamport.ResponseError as e:
       return JsonResponse({'error':e.message})
    

templates/payment/complete.html
{% extends 'base.html'%}

{% block title %}
주문완료
{% endblock %}

{% block content %}
    <h1>주문이 완료 되었습니다.</h1>
    <h3>
        고객님의 주문이 완료 되었습니다. <br/>
        고객님의 주문 번호는 {{order.id}} 입니다.
    </h3>
{% endblock %}

templates/payment/failed.html
{% extends 'base.html'%}

{% block title %}
주문완료
{% endblock %}

{% block content %}
    <h1>고객의 요청에 의해 주문이 실패 하였습니다.</h1>
    <h3>
        <a class="btn btn-lg btn-primary" href='{% url "shop:product_list" %}'>홈으로 돌아가기</a>
    </h3>
{% endblock %}

templates/payment/process.html
{% extends "base.html" %}
{% load static %}

{% block title %} 주문 결재 {% endblock %}

{% block script %}
    <script src="https://cdn.iamport.kr/v1/iamport.js"></script>
    
    <script type = "text/javascript">
       
        csrf_token = '{{csrf_token}}';

        document.addEventListener("DOMContentLoaded", function(e){
            e.preventDefault();
            
            var IMP = window.IMP;
            IMP.init('{{shop_id}}');

            var amount ="{{amount}}";
            var type = "{{type}}";

            var order_id = "{{order_id}}";
            var merchant_id = "{{merchant_id}}";
            var item_name ="{{item_name}}"

            // 결제 정보가 만들어졌으면 iamport로 실제 결제 시도
    
            if (merchant_id !== '') {
                IMP.request_pay({
                    merchant_uid: merchant_id,
                    name: item_name,
                    buyer_name: 'jisungs',
                    buyer_email:'jisungs@gmail.com',
                    amount: amount
                }, function (rsp) {
                    if (rsp.success) {
                        var msg = '결제가 완료되었습니다.';
                        msg += '\n고유ID : ' + rsp.imp_uid;
                        msg += '\n상점 거래ID : ' + rsp.merchant_uid;
                        msg += '\n결제 금액 : ' + rsp.paid_amount;
                        msg += '\n카드 승인번호 : ' + rsp.apply_num;
                        
                        // 결제가 완료되었으면 비교해서 디비에 반영
                        // ImpTransaction(e, order_id, rsp.merchant_uid, rsp.imp_uid, rsp.paid_amount);
                    ImpValidation(e, order_id, rsp.merchant_uid, rsp.imp_uid, rsp.paid_amount);
                    
                    } else if (rsp.success == false){
                        console.log('결재실패')
                        
                        return window.location.replace("{% url 'payment:failed'%}")
                    } 
                    else {
                        
                        var msg = '결제에 실패하였습니다.\n';
                        msg += '에러내용 : ' + rsp.error_msg;
                        console.log(msg)
                    }
                });
            }
        });


        function ImpValidation (e, order_id, merchant_id, imp_id,amount){
           // e.preverntDefault();

            console.log("결재 검증후 데이터 베이스 저장")

            fetch("{% url 'payment:validation'%}",{
                method:'POST',
                headers: {
                    'Content-Type': 'application/x-www-form-urlencoded',
                    'X-CSRFToken': csrf_token
                },

                body: new URLSearchParams({
                    order_id: order_id,
                    merchant_id: merchant_id,
                    imp_id: imp_id,
                    amount: amount})
                   
            })
            .then(rsp => rsp.json())
            .then(data=> {
                if(data.works){
                    //window.location.href = location.origin + '{% url "payment:completed"%}' + '?order_id='+ order_id;
                    var url = "{% url 'payment:completed' %}"+"?order_id="+ order_id
                    return window.location.replace(url)
                }
            })
            .catch(error => {
                if(error.status===404){
                    alert("페이지가 존재하지 않습니다.");
                }else if (error.status === 403){
                    alert("로그인해주세요");
                }else{
                    console.log(error)
                    alert("문제가 발생했습니다. 다시시도해주세요.");
                }
            })
        }
        

    </script>

{% endblock %}


{% block content %}

<h1>결재가 진행중입니다.</h1>

<a class="btn btn-lg btn-primary" href='{% url "shop:product_list" %}'>홈으로 돌아가기</a>
{% endblock %}